name: pull request

on:
  pull_request:
    branches: ['*']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}  # Checkout the PR branch

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pip install -e .

      - uses: pre-commit/action@v3.0.0
        env:
          SKIP: no-commit-to-branch

      - name: Run check-changelog hook manually
        run: |
          pre-commit run check-changelog --hook-stage pre-push --all-files --verbose

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .

      - name: Run tests
        run: |
          pytest
